import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import page from "./components/ui/DashboardNav"
const poppins = Poppins({ subsets: ["latin"], weight: "300" });
// testtttt
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={poppins.className}>{children}</body>
        </html>
    );
}
