import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import Navbar from "./components/Layout/Navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Providers } from "./Providers";
config.autoAddCss = false;

const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
