import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import Navbar from "../components/Layout/Navbar";
import DashboardNav from "../components/Layout/DashboardNav";

const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                {/* <Navbar /> */}
                <DashboardNav />
                {children}
            </body>
        </html>
    );
}
